version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge